name: Manual Inputs
on: 
  workflow_dispatch:
    inputs:
      version:
        description: Version
        default: v1.0.0
        required: true
jobs:
  bump-version:
    name: Bump Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Example variable usage
        run: echo hello,  ${{ github.event.inputs.version }}