name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container
      run: make build
    - name: Run black code format check
      run: make run_black_check
    - name: Run PyTest tests
      run: make run_pytest